### ISSUE TITLE
Fails with apps using hostname only

### ISSUE THREAD

**Issue by richardmoe** [martensson/moxy#1]
Apps using short url http://host seem to fail.

**Comment by martensson** [comment]
Fixed in https://github.com/mailgun/oxy/pull/17 , still waiting for merge :)

**Comment by martensson** [comment]
Now fixed in https://github.com/martensson/moxy/commit/8b11de3b1be502396dfb6ebb3458946c7a3a471c and https://github.com/mailgun/oxy/commit/d4d2ba4f5335b004293e4e31e4ba9475766e8b19 :)
