### ISSUE TITLE
moxy not updating when app get restarted/rescheduled

### ISSUE THREAD

**Issue by discordianfish** [martensson/moxy#2]
Hi,

let say I have a marathon app called 'foo' and I can reach it via moxy as 'foo.example.com'.
Now if I restart 'foo' via the marathon ui, it gets rescheduled to a different slave/port but moxy fails to update this so I get "Bad Gateway".
moxy doesn't log anything when reschduling 'foo'.

**Comment by martensson** [comment]
@discordianfish did you add moxy to you callbacks in Marathon? It needs to be notified that that the app 'foo' has a changed state :)

**Comment by discordianfish** [comment]
Ohh.. sorry, I missed that. Thanks for pointing it out!

**Comment by martensson** [comment]
No problem! :+1:
